### ISSUE TITLE
Incorrect parseTorrent return types

### ISSUE THREAD

**Issue by macrespo42** [webtorrent/parse-torrent#184]
**What version of this package are you using?**
"@types/parse-torrent": "^5.8.7"
"parse-torrent": "^11.0.16",

**What operating system, Node.js, and npm version?**
Os: Macos Sonoma
Nodejs version: v21.5.0
npm version: 10.2.4

**What happened?**
<img width="1386" alt="image" src="https://github.com/webtorrent/parse-torrent/assets/43120731/1c19d8e2-ce91-4818-860f-ce6edf6a9dfe">

**What did you expect to happen?**
The return types indicated is MagnetUri.instance or ParseTorrentFile.instance but the function return me a promise instead

**Comment by ThaUnknown** [comment]
thats a `@types/parse-torrent` issue, not us, we don't maintain that package
