### ISSUE TITLE
Get more info from magnet

### ISSUE THREAD

**Issue by Extarys** [webtorrent/parse-torrent#54]
It would be nice to be able to retrieve file lists, torrent name and total size and maybe peers from magnet. I'm trying to combine this with maybe bittorrent-tracker or bittorrent-dht.

**Comment by DiegoRBaquero** [comment]
That information is not in the magnet. You would need to fetch it from peers/xs

**Comment by Extarys** [comment]
Could you tell me how you would do it ?

**Comment by DiegoRBaquero** [comment]
Use webtorrent and once metadata is available, destroy torrent.

**Comment by Extarys** [comment]
Huh, thanks!
