### ISSUE TITLE
Possible to parse a torrent file, change the name, then recreate torrent file?

### ISSUE THREAD

**Issue by guanzo** [webtorrent/parse-torrent#73]
Hi. All I want to do is change the name of a torrent file, without having to feed `create-torrent` the entire file again. Can I simply parse a torrent file, change the `name` key, then call `parseTorrent.toTorrentFile`?

It looks like the `encodeTorrentFile ` function doesn't check the `name` of the `parsed` argument, so i'm not sure how to proceed. It does check `parsed.info`, but that seems to be different than the top level keys found in the `create-torrent` options, which is where the `name` option is set.
https://github.com/webtorrent/parse-torrent/blob/6286abb3361bd0662bb93a1686eff28701b6f59a/index.js#L195-L198

**Comment by KayleePop** [comment]
Try changing `info.name` instead
