### ISSUE TITLE
Warnings installing the latest version

### ISSUE THREAD

**Issue by PaTiToMaSteR** [webtorrent/parse-torrent#82]
**What version of this package are you using?**
latest, 7.1.2

**What operating system, Node.js, and npm version?**
Linux CentOS 7 - npm 6.14.4

**What happened?**
versions not compatible while installing

**What did you expect to happen?**
install without warnings or errors

**Are you willing to submit a pull request to fix this bug?**
I have not this knowledge

/usr/bin/parse-torrent -> /usr/lib/node_modules/parse-torrent/bin/cmd.js
npm WARN notsup Unsupported engine for get-stdin@7.0.0: wanted: {"node":">=8"} (current: {"node":"6.17.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: get-stdin@7.0.0
npm WARN notsup Unsupported engine for decompress-response@4.2.1: wanted: {"node":">=8"} (current: {"node":"6.17.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: decompress-response@4.2.1
npm WARN notsup Unsupported engine for mimic-response@2.1.0: wanted: {"node":">=8"} (current: {"node":"6.17.1","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: mimic-response@2.1.0

**Comment by DiegoRBaquero** [comment]
You have old node, please update node.
